# Generated by Django 3.1.2 on 2020-11-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0003_auto_20201108_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.DateTimeField(null=True, verbose_name='payment_status'),
        ),
    ]
