# Generated by Django 3.1.2 on 2020-10-24 19:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_auto_20201023_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserprofile',
            name='localization',
            field=models.CharField(blank=True, max_length=30, verbose_name='localization'),
        ),
        migrations.AddField(
            model_name='shopuserprofile',
            name='social_page',
            field=models.TextField(blank=True, max_length=512, verbose_name='social page'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 26, 19, 34, 3, 521733, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='age',
            field=models.PositiveSmallIntegerField(default=18, verbose_name='age'),
        ),
    ]
