# Generated by Django 3.1.2 on 2020-11-17 20:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0028_auto_20201117_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 20, 34, 34, 285359, tzinfo=utc)),
        ),
    ]
