# Generated by Django 3.1.2 on 2020-10-28 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cartapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='product',
            new_name='game',
        ),
    ]
